### PR TITLE
#169 added a new message with final grading due date

### LINKED ISSUE #169: Misleading message: grading completed
When grading is completed, CAPQuiz displays the message «Grading is completed.
You achieved 0 stars, which is a failing grade.» on every question.
This is annoying and may mislead the student into thinking that something is wrong. This should  be removed or rephrased. If displayed there should definitely be a reference to the deadline. Grading is complete only in the sense that the deadline for official grading is passed.

To devise the best solution here, we need some knowledge about how and when the message is created.

### PR DESCRIPTION
**Pull request by sushanthko**
Fixes #169

### CODE REVIEW

File: classes/capquiz.php [hunk 1]
```diff
@@ -82,6 +82,10 @@ public function is_grading_completed() : bool {
         return $this->record->timedue < time() && $this->record->timedue > 0;
     }
 
+    public function duedate() : string {
+        return date('d-m-Y', $this->record->timedue);
+    }
+
```
Comment (andstor) [inline classes/capquiz.php]: Remove this function in favor for the Moodle guidelines. This way, the date won't be localized.

File: classes/output/question_attempt_renderer.php [hunk 2]
```diff
@@ -127,7 +127,8 @@ public function render_question_attempt(capquiz_question_attempt $attempt, \ques
             ],
             'gradingdone' => $this->capquiz->is_grading_completed(),
             'finalgrade' => $this->capquiz->user()->highest_stars_graded(),
-            'gradingpass' => $this->capquiz->user()->highest_stars_graded() >= $this->capquiz->stars_to_pass()
+            'gradingpass' => $this->capquiz->user()->highest_stars_graded() >= $this->capquiz->stars_to_pass(),
+            'duedate' => $this->capquiz->duedate()
```
Comment (andstor) [inline classes/output/question_attempt_renderer.php]: Use something like `get_string('strftimedate', 'capquiz')` here instead of `duedate()`.
One would have to add the `strftimedate`to the language file: `$string['strftimedate'] = '%d %B %Y';`
```suggestion
            'duedate' => $this->capquiz->get_string('strftimedate', 'capquiz');
```

Comment (sushantk-stud) [reply classes/output/question_attempt_renderer.php]: Will make the changes.

File: classes/capquiz.php [hunk 3]
```diff
@@ -82,6 +82,10 @@ public function is_grading_completed() : bool {
         return $this->record->timedue < time() && $this->record->timedue > 0;
     }
 
+    public function duedate() : string {
+        return userdate($this->record->timedue, get_string('strftimedatetime', 'langconfig'));
+    }
+
```
Comment (andstor) [inline classes/capquiz.php:88]: The `capquiz` class is only meant to keep data about a CAPQuiz (mostly data mappings). I think this function should be removed, and the logic moved to the `question_attempt_renderer.php` file.
```suggestion
```

File: classes/output/question_attempt_renderer.php (hunk 2 above)
Comment (andstor) [inline classes/output/question_attempt_renderer.php:131]:
```suggestion
            'duedate' => userdate($this->capquiz->time_due(), get_string('strftimedatetime', 'langconfig'));
```

**Review by andstor — APPROVED** [review]
